### ISSUE TITLE
Launch a quickstart repo

### ISSUE THREAD

**Issue by amcgivern** [flexpa/quickstart#1]
### Why
- Quickstart repos are a great way to get developers started with Flexpa. They provide devs with the ability to see how easy the library is to work with and immediately allow them to experiment with it. 
- Opportunity for prospective devs to learn by doing

### What
- [x] Create a new public repo 
- [x] Add flexpa/link to the repo and ensure the user can log in using a test mode API key pair
- [x] Add a call to flexpa/api `/link/exchange` route to receive the access token
- [x] Send a request to retrieve a FHIR resource from flexpa/api using `fetch` and the access token
- [x] Add documentation describing how to clone and run the repo
- [x] Write Changelog entry in /docs/changelog, + adding NEW tag for Quickstart in menu, removing others (except changelog itself which is new by default)
- [x] GH Quickstart repo should back-link / promote entry paths back into Flexpa (linking to docs / 1-sentence pitch, Discord link?, other branding)
- [ ] Prepare Adarsh on the parts this has (changelog, Quickstart link, Github repo) so he can re-use in future communications + announcement

Notes:
- The project should be simple and easy to set up regardless of OS
	-  [x] Project should be clonable
    -  [x] Should probably only require you to have an API key pair
- Project infrastructure steps that are important
	- [x] Configuring dependency updates (Github Action)
    - [x] Branch protection settings (ex. requiring an approval, passing status checks)
- Quickstart project tooling/dependencies should be pretty familiar to us
	- Uses plain Javascript so it's easily understandable by most developers
- It's important for users to understand that they require both a front and back end to use Flexpa. 
	- Using Vite for the frontend and Express on the backend since they are simple frameworks and clearly indicate that a client and server are required

Some examples for reference:
- https://plaid.com/docs/quickstart/, https://github.com/plaid/quickstart

**Comment by jdjkelly** [comment]
To complete "launch", I am suggesting:
* Writing Changelog entry in /docs/changelog, + adding NEW tag for Quickstart in menu, removing others (except changelog itself which is new by default)
* GH Quickstart repo should back-link / promote entry paths back into Flexpa (linking to docs / 1-sentence pitch, Discord link?, other branding)
* Prepare Adarsh on the parts this has (changelog, Quickstart link, Github repo) so he can re-use in future communications + announcement
